### ISSUE TITLE
Create habitat plan for customized ansible

### ISSUE THREAD

**Issue by lottspot** [CodeForPhilly/civic-cluster#4]
Ansible requires the `openshift` python module in order to talk to kubernetes clusters, which is a native module. Due to that fact, we can't simply `pip install` that module inside of the studio environment. We will instead need a custom habitat plan (civic-cloud-ansible, or something) to build ansible along with all of the modules we require (currently just `openshift`).

**Comment by lottspot** [comment]
A blueprint: https://github.com/JarvusInnovations/habitat-core-plans/blob/netdata-mysql/netdata/plan.sh

**Comment by themightychris** [comment]
Some good reference points:

- Reference page with all the stuff you can do it plans: https://www.habitat.sh/docs/reference/
- The intro to writing plans: https://www.habitat.sh/docs/developing-packages/
- The source code for all the official plans: https://github.com/habitat-sh/core-plans
  - this is possibly the most underlooked and most valuable resource, clone this repo locally and code search inside it constantly, use github's blame view to read how plans got how they are

**Comment by lottspot** [comment]
Done in [ops 770041c](https://github.com/CodeForPhilly/ops/commit/770041c9bdd67565ba77a765b527ec65fe3ba4bd)
